/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.TelaPrinLivro;
import model.dao.TelaPrinLivroDao;

/**
 *
 * @author PC-000
 */
public class TelaPrincipalLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalLivro
     */
    public TelaPrincipalLivro() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableLivro.getModel();
        jTableLivro.setRowSorter(new TableRowSorter(modelo));
        readTelaLivros();
    }
    public void readTelaLivros(){
        DefaultTableModel modelo = (DefaultTableModel) jTableLivro.getModel();
        modelo.setNumRows(0);
        TelaPrinLivroDao ldao = new TelaPrinLivroDao();
        
        for (TelaPrinLivro l: ldao.read()){
            modelo.addRow(new Object[]{
                l.getId(),
                l.getNome_livro(),
                l.getNome_autor(),
                l.getEditora(),
                l.getData_publicacao(),
                l.getNumero_paginas()
            });
        
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTelaPrinLivro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textEditora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textDataPub = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textNumeroPaginas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLivro = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        labelPesquisa = new javax.swing.JLabel();
        textBusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JTelaPrinLivro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(15, 113, 183));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Livros");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(545, 545, 545))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        textNome.setBackground(new java.awt.Color(255, 255, 255));
        textNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textNome.setForeground(new java.awt.Color(102, 102, 102));
        textNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(15, 113, 183)));
        textNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(15, 113, 183));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 113, 183));
        jLabel2.setText("Nome");
        jLabel2.setToolTipText("");

        textAutor.setBackground(new java.awt.Color(255, 255, 255));
        textAutor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textAutor.setForeground(new java.awt.Color(102, 102, 102));
        textAutor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(15, 113, 183)));
        textAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAutorActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(15, 113, 183));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(15, 113, 183));
        jLabel3.setText("Autor");
        jLabel3.setToolTipText("");

        textEditora.setBackground(new java.awt.Color(255, 255, 255));
        textEditora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textEditora.setForeground(new java.awt.Color(102, 102, 102));
        textEditora.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(15, 113, 183)));
        textEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEditoraActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(15, 113, 183));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 113, 183));
        jLabel4.setText("Editora");
        jLabel4.setToolTipText("");

        textDataPub.setBackground(new java.awt.Color(255, 255, 255));
        textDataPub.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(15, 113, 183)));
        textDataPub.setForeground(new java.awt.Color(102, 102, 102));
        try {
            textDataPub.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        textDataPub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textDataPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDataPubActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(15, 113, 183));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(15, 113, 183));
        jLabel5.setText("Data Publicação");

        jLabel6.setBackground(new java.awt.Color(15, 113, 183));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(15, 113, 183));
        jLabel6.setText("Nº Páginas");
        jLabel6.setToolTipText("");

        textNumeroPaginas.setBackground(new java.awt.Color(255, 255, 255));
        textNumeroPaginas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textNumeroPaginas.setForeground(new java.awt.Color(102, 102, 102));
        textNumeroPaginas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(15, 113, 183)));
        textNumeroPaginas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeroPaginasActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Adicionar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Excluir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Atualizar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 166, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        jTableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do livro", "Nome do  autor", "Editora", "Data Publicação", "Numero De Paginas"
            }
        ));
        jTableLivro.setGridColor(new java.awt.Color(255, 255, 255));
        jTableLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLivro);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        labelPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        labelPesquisa.setForeground(new java.awt.Color(255, 255, 255));
        labelPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_search_50px_1.png"))); // NOI18N
        labelPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPesquisaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPesquisaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPesquisaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(labelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        textBusca.setBackground(new java.awt.Color(255, 255, 255));
        textBusca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textBusca.setForeground(new java.awt.Color(102, 102, 102));
        textBusca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(15, 113, 183)));
        textBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JTelaPrinLivroLayout = new javax.swing.GroupLayout(JTelaPrinLivro);
        JTelaPrinLivro.setLayout(JTelaPrinLivroLayout);
        JTelaPrinLivroLayout.setHorizontalGroup(
            JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                        .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNome, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textAutor)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textEditora)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textDataPub, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNumeroPaginas)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JTelaPrinLivroLayout.setVerticalGroup(
            JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JTelaPrinLivroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                        .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JTelaPrinLivroLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textDataPub, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JTelaPrinLivroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)))
                .addGroup(JTelaPrinLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTelaPrinLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 1102, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTelaPrinLivro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAutorActionPerformed

    private void textEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEditoraActionPerformed

    private void textDataPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataPubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataPubActionPerformed

    private void textNumeroPaginasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeroPaginasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeroPaginasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTableLivro.getSelectedRow() != -1) {
                
            TelaPrinLivro c = new TelaPrinLivro();
            TelaPrinLivroDao dao = new TelaPrinLivroDao();
            
            c.setNome_livro(textNome.getText());
            c.setNome_autor(textAutor.getText());
            c.setEditora(textEditora.getText());
            String dia = textDataPub.getText().substring(0,2);
            String mes = textDataPub.getText().substring(5,6);
            String ano = textDataPub.getText().substring(6,7);
            c.setData_publicacao(ano+"-"+mes+"-"+"-"+dia);
            c.setNumero_paginas(Integer.parseInt(textNumeroPaginas.getText()));
            c.setId((int) jTableLivro.getValueAt(jTableLivro.getSelectedRow(),0));
            dao.update(c);
            
            textNome.setText(""); 
            textAutor.setText("");
            textEditora.setText(""); 
            textNumeroPaginas.setText(""); 
            textDataPub.setText(""); 
            readTelaLivros();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //aqui
        TelaPrinLivro pl = new TelaPrinLivro();
        TelaPrinLivroDao pld = new TelaPrinLivroDao();
        
        pl.setNome_livro(textNome.getText());
        pl.setNome_autor(textAutor.getText());
        pl.setEditora(textEditora.getText());
        String dia = textDataPub.getText().substring(0,2);
        String mes = textDataPub.getText().substring(3,5);
        String ano = textDataPub.getText().substring(6);
        pl.setData_publicacao(ano+"-"+mes+"-"+"-"+dia);
        pl.setNumero_paginas(Integer.parseInt(textNumeroPaginas.getText())); 
        
        pld.create(pl);
        
        textNome.setText(""); 
        textAutor.setText("");
        textEditora.setText(""); 
        textNumeroPaginas.setText(""); 
        textDataPub.setText(""); 
        readTelaLivros();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void readTelaPrinLivro(String nome){
        DefaultTableModel modelo = (DefaultTableModel) jTableLivro.getModel();
        modelo.setNumRows(0);
        TelaPrinLivroDao ldao = new TelaPrinLivroDao();
        
        for (TelaPrinLivro l: ldao.readForDes(nome)){
            modelo.addRow(new Object[]{
                l.getId(),
                l.getNome_livro(),
                l.getNome_autor(),
                l.getEditora(),
                l.getData_publicacao(),
                l.getNumero_paginas()
            });
        }
    
    }
    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        //adicionar
        setColor(jButton1);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        //adicionar
        resetColor(jButton1);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        //excluir
        setColor(jButton2);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        //excluir
        resetColor(jButton2);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        //atualizar
        setColor(jButton3);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        //atualizar
        resetColor(jButton3);
    }//GEN-LAST:event_jButton3MouseExited

    private void textBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBuscaActionPerformed

    private void jTableLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivroMouseClicked
        // TODO add your handling code here:
        if (jTableLivro.getSelectedRow() != -1) {
            textNome.setText(jTableLivro.getValueAt(jTableLivro.getSelectedRow(),1).toString());
            textAutor.setText(jTableLivro.getValueAt(jTableLivro.getSelectedRow(),2).toString());
            textEditora.setText(jTableLivro.getValueAt(jTableLivro.getSelectedRow(),3).toString());
            textDataPub.setText(jTableLivro.getValueAt(jTableLivro.getSelectedRow(),4).toString());
            textNumeroPaginas.setText(jTableLivro.getValueAt(jTableLivro.getSelectedRow(),5).toString());
        }
    }//GEN-LAST:event_jTableLivroMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTableLivro.getSelectedRow() != -1) {
                
            TelaPrinLivro c = new TelaPrinLivro();
            TelaPrinLivroDao dao = new TelaPrinLivroDao();
            
            c.setId((int) jTableLivro.getValueAt(jTableLivro.getSelectedRow(),0));
            dao.delete(c);
            
            textNome.setText(""); 
            textAutor.setText("");
            textEditora.setText(""); 
            textNumeroPaginas.setText(""); 
            textDataPub.setText(""); 
            readTelaLivros();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void labelPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPesquisaMouseClicked
        // TODO add your handling code here:
        
        //aqui
        readTelaPrinLivro(textBusca.getText());
    }//GEN-LAST:event_labelPesquisaMouseClicked

    private void labelPesquisaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPesquisaMouseEntered
        // TODO add your handling code here:
        //busca
        setColor(labelPesquisa);
    }//GEN-LAST:event_labelPesquisaMouseEntered

    private void labelPesquisaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPesquisaMouseExited
        // TODO add your handling code here:
        //busca
        resetColor(labelPesquisa);
    }//GEN-LAST:event_labelPesquisaMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        //busca
        setColor(jPanel3);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        //busca
        resetColor(jPanel3);
    }//GEN-LAST:event_jPanel3MouseExited
     
            
    public void setColor(JButton panel){
        panel.setBackground(new java.awt.Color(115,163,239));
        
    }
    public void resetColor(JButton panel){
        panel.setBackground(new java.awt.Color(240,240,240));
        
    }
    
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(115,163,239));
        
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(240,240,240));
        
    }
    public void setColor(JLabel label){
        label.setBackground(new java.awt.Color(115,163,239));
        
    }
    public void resetColor(JLabel label){
        label.setBackground(new java.awt.Color(240,240,240));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JTelaPrinLivro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLivro;
    private javax.swing.JLabel labelPesquisa;
    private javax.swing.JTextField textAutor;
    private javax.swing.JTextField textBusca;
    private javax.swing.JFormattedTextField textDataPub;
    private javax.swing.JTextField textEditora;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumeroPaginas;
    // End of variables declaration//GEN-END:variables
}
